import type { Metadata } from "next";
import { FloatingDockDemo } from "@/components/FloatingNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <FloatingDockDemo />

      {children}
    </>
  );
}
